courselab/coral

coral.py

Added feature #11 , where the snake's starting positions are random, but not too close to the border where it is heading to.
This was done by generating a random number between` GRID_SIZE * 2` and `PROPORTION - GRID_SIZE * 2 `, which means that the snake will not be closer than 2 squares from the border. Also, the initial direction of movement is not directed towards the edges of the screen.

Feature: snake starting in a random position

---

coral.py

An EnergyBar class that contains the functionalities has been created.
Energy bar feature and its mechanics have been added.

code: energy bar

---

coral.py

#21 An option to start the game in harm mode, almost doubling the speed of the snake.
#22 Fixed to Merging on to dev and not main

Adding Hard Mode

---

coral.py

Now the energy bar works correctly, regardless of the initial amount of power.

fix: energy bar size

---

coral.py

This PR implements "Easy Mode" where the snake wraps around the screen borders, activated by pressing `E` on the start menu. Addresses issue #48

Feature: Easy Mode with Border Wrap

---

coral.py

Added cute head and tail for the snake

feat: adding stylized head and tail

---

coral.py

Added changes that fix issue #38 with snake movement during rapid key presses:
- Added a movement queue to the snake class to store movement commands during key presses
- Now, at each update() call, a movement command is popped from the queue and executed
- Movement is now smoother and more responsive allowing for quicker and more complex moves from the player

Fix issue with snake movement #38

---

coral.py

Add code that implements the feature mentioned on issue #56
- Draw a new box "Volume" in the configuration menu
- The user can now choose between 3 presets that multiply the base volume
- The volume power changes the same time as the user changes the config

Implement volume changing in configuration menu

---

coral.py

changed the apple to make it look circular

feat: make the apple circular

---

coral.py

I added a screen with instructions on how to play that can be accessed by pressing the letter I on the game screen

code: adding an instruction screen while the game runs

---

coral.py

This PR closes issue #57 by adding a win condition: when the snake fills the entire game screen, a win screen is displayed. This provides a satisfying endpoint for players looking to complete the game by occupying the full area.

feat: add win condition

---

coral.py

Fixes #74 
Updated the initial prompt to 'Press any key to start' for greater clarity and precision

improving initial description

---

app/fruits/fruitBase.py
app/orange.py

refactoring fruits to use a base class 

---

app/main.py

Refactoring movement keyboard input

---

AUTHORS
app/config.py
app/energybar.py
app/game.py
app/main.py
app/snake.py
app/translation.py
assets/translation.json

Adds supports for multiple languages standardizing every message

Add multiple language support

---

app/snake.py

improving restart description

---

app/main.py

Change comments to English

---

AUTHORS

Included myself and ordered the list of authors alphabetically. Maybe solves [144](https://github.com/courselab/coral/issues/144).

doc: Updated AUTHORS

---

app/game.py
app/main.py

Solves [148](https://github.com/courselab/coral/issues/148). Text adequately positioned and resized considering the new font's dimensions.

fix: resize text

---

app/main.py
app/obstacles.py

Solves [166](https://github.com/courselab/coral/issues/166). Also modified its spawn logic so that it never spawns at the snake's initial path.

fix: Obstacles now kill on contact

---

AUTHORS

doc: Includes me. Contributing to milestone v1.0.0.

---

AUTHORS

This Pull Request addresses issue #144.
Added my name to the AUTHORS file as part of the preparation for the upcoming release.

doc: add name to AUTHORS file

---

AUTHORS

Add author #144

---

app/game.py
app/snake.py

In the menu, I added new color options for the snake (blue, red, and yellow). I tested all of them, and apparently, they're working well.

Add new color options in menu

---

assets/translation.json

reimplemented #162 fixing the conflicts.

minor: fixed restart text.

---

musics/CPU Talk - FMA - CC BY BoxCat Games.mp3.license
musics/game_over.wav.license
musics/got_apple.ogg.license

Attached licensing information to each of the audios. Solves #145 .

chore: Added licensing text to audios
